INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('crunchytaco', 'Taco', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('alive_chicken', 'Live Chicken', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('bait', 'Worms', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('fish', 'Fish', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('fishingrod', 'Fishing Rod', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('bandage', 'Bandage', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('firstaid', 'Med Bag', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('medikit', 'Med Kit', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('beer', 'Beer', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('grand_cru', 'Champagne', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('rhum', 'Rum', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('rhumcoca', 'Rum & Coka', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('betequilaer', 'Margarita', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('vine', 'Wine', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('wine', 'Red Wine', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('vodka', 'Vodka', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('whisky', 'Whisky', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('whiskycoca', 'Whisky & coka', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('black_chip', 'ROM Chip', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('electronics', 'EPROM Chip', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('tunerlaptop', 'Laptop', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('radio', 'Radio', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('bolchips', 'Lays Chips', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('chips', 'Chips', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('cheesebows', 'Chesse Puffs', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('bolnoixcajou', 'Cajou', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('bolpistache', 'Pistaches', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('bolcacahuetes', 'Roasted Peanuts', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('caprisun', 'Capri Sun', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('cocacola', 'Coca Cola', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('coffee', 'Coffee', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('fanta', 'Fanta', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('energy', 'Energy Drink', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('soda', 'Dr Pepper', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('redbull', 'Red Bull', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('chocolate', 'Chocolate', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('cupcake', 'Cup Cake', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('cigarett', 'Cigarette', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('chickensandwich', 'Chicken Sandwich', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('moneyshot', 'Bleeder', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('heartstopper', 'Heart Stopper', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('hamburger', 'DBL Bacon Bleeder', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('pizza', 'Pizza', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('fries', 'Fries', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('gatorade', 'Gatorade', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('cocaine', 'Cocaine', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('cokeounce', 'Coke', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('cokebrick', 'Coke Brick', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('weedseed', 'Weed Seed', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('cannabis', 'Weed Bud', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('weedeight', 'Weed Baggie', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('weedqtr', 'Weed Brick', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('joint', 'Joint', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('cash', 'Cash', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('cchip', 'Poker Chips', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('contrat', 'Contrat', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('fakeplates', 'Fake Plates', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('gauze', 'Gauze', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('grapperaisin', 'Grappe Raisin', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('goldchain', 'Gold Chain', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('goldring', 'Gold Ring ', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('jewels', 'Jewels', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('raisin', 'Grappe', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('lotteryticket', 'Lottery Ticket', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('lighter', 'Lighter', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('ice', 'Ice', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('jusfruit', 'Grappe Juice', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('shark', 'Shark', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('turtle', 'Turtle', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('turtlebait', 'Turtle Bait', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('saucisson', 'Saucisson', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('rawgold', 'Raw Gold', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('slaughtered_chicken', 'Whole Chicken', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('watch', 'Watch', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('packaged_chicken', 'Packaged Chicken', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('hydrocodone', 'Hydrocodone', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('morphine', 'Morphone', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('oxy', 'Oxycodone', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('pills', 'Pills', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('meth', 'Meth', 1, 0, 1);
INSERT IGNORE INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('meth_pooch', 'Meth Brick', 1, 0, 1);